### PR TITLE
Feature/evo 3237 jc send file parser

### PR DESCRIPTION
**Pull request by jacobchristensen79**
Just uploading again the changes for comparison reasons.

### CODE REVIEW

**Comment by hairmare** [comment]
Mate, THis is just as non-functional as both #18 and #19 where. It's also lacking tests just as all the PRs that came before it.

**Comment by hairmare** [comment]
FYI the stuff in #20 build upon these changes, fixes them so they actually work and adds tests for the code in `Graviton\ImportExport\Service\HttpClient`. It also renames the class since it rewrites it to not extend the guzzle base class. I consider extending classes from libs in that manner as unmaintainable.

**Comment by jacobchristensen79** [comment]
FYI, the tests are the same as it was for Guzzle. I extend it as we also do our own way in graviton. And as said, I could do a "TransferManager" and inject Guzzle there. But considered not to so "old" tests could run on the same and be sure it was back compatible. You say something is not working, if "old" test that runs this code works what is that was not tested previously and what is it that is not working. This is now in third party "hands".

**Comment by narcoticfresh** [comment]
i was asked to merge either #20 or #21.. 

they both archieve the same, #20 is better that it updates all deps (especially `phpunit`), but this one archieves the same with less changes..

I could confirm this PR works, also with the `-s` switch I couldn't find any functional problems.. So it's more like a *flip a coin* decision..

So I bumped all deps here, updated to new phpunit mock API and let's get this merged..

**Pull request merged**
